"""moved train line from Train Profile to facts table

Revision ID: 69c46e6bef93
Revises: 5b28532a5fca
Create Date: 2026-01-18 13:59:30.298992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69c46e6bef93'
down_revision: Union[str, Sequence[str], None] = '5b28532a5fca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('_train_profile_uc'), 'dim_train_profiles', type_='unique')
    op.create_unique_constraint('_train_profile_uc', 'dim_train_profiles', ['train_number', 'train_type'])
    op.drop_column('dim_train_profiles', 'train_line')
    op.add_column('fact_train_stops', sa.Column('train_line', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fact_train_stops', 'train_line')
    op.add_column('dim_train_profiles', sa.Column('train_line', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_constraint('_train_profile_uc', 'dim_train_profiles', type_='unique')
    op.create_unique_constraint(op.f('_train_profile_uc'), 'dim_train_profiles', ['train_number', 'train_line', 'train_type'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
