"""sync models

Revision ID: 90791f453d45
Revises: 317d8c0da1ff
Create Date: 2025-12-13 20:17:35.227205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90791f453d45'
down_revision: Union[str, Sequence[str], None] = '317d8c0da1ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('dim_train_profiles_train_number_train_line_train_type_key'), 'dim_train_profiles', type_='unique')
    op.create_unique_constraint('_train_profile_uc', 'dim_train_profiles', ['train_number', 'train_line', 'train_type'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_train_profile_uc', 'dim_train_profiles', type_='unique')
    op.create_unique_constraint(op.f('dim_train_profiles_train_number_train_line_train_type_key'), 'dim_train_profiles', ['train_number', 'train_line', 'train_type'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
