name: DIA_2025_26 #included to prevent name collision on volumes and networks across multiple projects
services:
  app:
    container_name: dia_eval
    build:
      context: ..
      dockerfile: Dockerfile
      target: production
    env_file:
      - ../env/postgres.env
      - ../env/pgadmin.env
    depends_on:
      - db:
          condition: service_healthy
    stdin_open: true # Docker starts containers in a non-interactive mode by default, bin/bash is interactive. This tells Docker to keep the STDIN open for the container.
    tty: true        # where the container sends the output from its processes. This allocates a pseudo-TTY, which is necessary for interactive sessions like bash.

  db:
    image: postgres:latest
    env_file:
      - ../env/postgres.env
    volumes:
      - pgdata_prod:/var/lib/postgresql/data #dedicated prod volume to avoid conflicts with devcontainer volume, easier debugging
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata: